# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-23 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_1', models.CharField(max_length=100)),
                ('player_2', models.CharField(max_length=100)),
                ('embed', models.CharField(blank=True, help_text='YouTube embed code', max_length=120, null=True)),
                ('pgn', models.CharField(max_length=250)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
