# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-23 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='unique',
            field=models.CharField(blank=True, help_text='YouTube embed code', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='embed',
            field=models.CharField(blank=True, help_text='YouTube embed link', max_length=120, null=True),
        ),
    ]
