# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-23 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_clicked'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameembed',
            field=models.CharField(blank=True, help_text='Lichess embed link', max_length=120, null=True),
        ),
    ]
